apiVersion: v1
kind: Service
metadata:
  name: loadmanager
  labels:
    app: loadmanager
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5001
    protocol: TCP
  selector:
    app: loadmanager
