apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: loadmanager-pod-lister
  namespace: default
subjects:
- kind: ServiceAccount
  name: loadmanager-sa
  namespace: default
roleRef:
  kind: Role
  name: pod-lister
  apiGroup: rbac.authorization.k8s.io
