apiVersion: apps/v1
kind: Deployment
metadata:
  name: loader
  labels:
    app: loader
spec:
  replicas: 30
  selector:
    matchLabels:
      app: loader
  template:
    metadata:
      labels:
        app: loader
    spec:
      containers:
      - name: loader
        image: tiriyon/loader:t0.0.8
        resources:
          requests:
            cpu: "300m"
            memory: "150Mi"
          limits:
            cpu: "350m"
            memory: "200Mi"
        ports:
        - containerPort: 5000
        env:
        - name: MEMORY_LIMIT_MB
          value: "190"

